name: Build and push docker images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          TAGS=""
          IMAGE="GoliathLabs/traefik-custom-error-pages"
          if [[ "$GITHUB_REF" == refs/heads/master ]]; then
            TAGS="$IMAGE:master"
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            TAGS="$IMAGE:$VERSION"
            if [[ ! "$VERSION" =~ -rc.* ]]; then
              TAGS="$TAGS,$IMAGE:latest"
            fi
          fi
          echo "building ref: $GITHUB_REF"
          echo "docker images: $TAGS"
          echo ::set-output name=tags::${TAGS}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: image=moby/buildkit:v0.9.0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx- 